# $FreeBSD: releng/10.2/usr.sbin/bsdconfig/includes/Makefile 279611 2015-03-05 00:34:33Z dteske $

NO_OBJ=

SUBDIR= include

FILESDIR=	${LIBEXECDIR}/bsdconfig/includes
FILES=		INDEX USAGE

SCRIPTSDIR=	${FILESDIR}
SCRIPTS=	includes

.include <bsd.prog.mk>
