# $FreeBSD: releng/10.2/usr.sbin/bsdinstall/scripts/Makefile 276486 2014-12-31 23:25:37Z ngie $

SCRIPTS= auto adduser checksum config docsinstall entropy hostname jail \
	 keymap mirrorselect mount netconfig netconfig_ipv4 netconfig_ipv6 \
	 rootpass script services time umount wlanconfig zfsboot
BINDIR= /usr/libexec/bsdinstall

MAN=

.include <bsd.prog.mk>
