#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: releng/10.2/usr.sbin/lpr/filters/Makefile 276486 2014-12-31 23:25:37Z ngie $

BINDIR=	/usr/libexec/lpr

PROG=	lpf
MAN=

CFLAGS+= -I${.CURDIR}/../common_source

.include <bsd.prog.mk>
