# Makefile for ntpd.
# $FreeBSD: releng/10.2/usr.sbin/ntp/Makefile 285612 2015-07-15 19:21:26Z delphij $

SUBDIR=	libopts libntp libntpevent libparse ntpd ntpdc ntpq ntpdate \
	ntptime ntp-keygen sntp
SUBDIR+=	doc

.include <bsd.subdir.mk>
