# $FreeBSD: releng/10.2/gnu/usr.bin/cc/collect2/Makefile 276486 2014-12-31 23:25:37Z ngie $

.include "../Makefile.inc"

.PATH: ${GCCDIR}

PROG=	collect2
SRCS=	collect2.c tlink.c version.c
MAN=

.include <bsd.prog.mk>
